const j=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
const now=()=>new Date().toISOString(),uid=()=>crypto.randomUUID(),caseNo=r=>`RISK-${new Date(r.created_at).getUTCFullYear()+543}-${String(r.seq).padStart(3,"0")}`;
const riskOut=r=>({...r,caseNo:caseNo(r),incidentDate:r.incident_date,incidentTime:r.incident_time,riskGroup:r.risk_group,safetyCategory:r.safety_category,riskCode:r.risk_code,eventTitle:r.event_title,eventDetail:r.event_detail,immediateAction:r.immediate_action,isPriority:!!r.is_priority,review:{reviewer:r.reviewer,reviewDate:r.review_date,rootCause:r.root_cause,contributingFactors:r.contributing_factors,correctiveAction:r.corrective_action,owner:r.owner,dueDate:r.due_date,outcome:r.outcome,residualSeverity:r.residual_severity,followUpDate:r.follow_up_date,lessonsLearned:r.lessons_learned}});
export default{async fetch(req,env){const u=new URL(req.url),p=u.pathname,m=req.method;try{
if(p==="/api/health")return j({ok:true});
if(p==="/api/migration-status"&&m==="GET"){const a=await env.DB.prepare("SELECT COUNT(*) n FROM risks").first(),b=await env.DB.prepare("SELECT COUNT(*) n FROM quality_documents").first();return j({risks:Number(a?.n||0),quality_documents:Number(b?.n||0)})}
if(p==="/api/risks/list"&&m==="GET"){const {results}=await env.DB.prepare("SELECT * FROM risks ORDER BY seq DESC").all();return j({items:results.map(riskOut),risks:results.map(riskOut)})}
if(p==="/api/risks/create"&&m==="POST"){const b=await req.json();if(!b.incidentDate||!String(b.unit||"").trim()||!String(b.eventTitle||"").trim()||!String(b.eventDetail||"").trim())return j({error:"missing_required_fields"},400);if(!["clinical","general"].includes(b.riskGroup)||(b.riskGroup==="clinical"?!/^[A-I]$/.test(b.severity||""):!/^[1-5]$/.test(b.severity||"")))return j({error:"invalid_risk_classification"},400);const n=await env.DB.prepare("SELECT COALESCE(MAX(seq),0)+1 n FROM risks").first(),id=uid(),t=now();await env.DB.prepare("INSERT INTO risks(id,seq,incident_date,incident_time,reporter,unit,location,risk_group,safety_category,risk_code,event_title,event_detail,immediate_action,severity,is_priority,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'reported','',?,?)").bind(id,Number(n.n),b.incidentDate,b.incidentTime||null,String(b.reporter||""),String(b.unit).trim(),String(b.location||""),b.riskGroup,String(b.safetyCategory||""),String(b.riskCode||""),String(b.eventTitle).trim(),String(b.eventDetail).trim(),String(b.immediateAction||""),String(b.severity),b.isPriority?1:0,t,t).run();const row=await env.DB.prepare("SELECT * FROM risks WHERE id=?").bind(id).first();return j({id,caseNo:caseNo(row)},201)}
let x=p.match(/^\/api\/risks\/([^/]+)$/);if(x&&m==="PUT"){const b=await req.json(),v=b.review||{};if(!String(v.reviewer||"").trim()||!String(v.rootCause||"").trim()||!String(v.correctiveAction||"").trim())return j({error:"missing_review_fields"},400);if(!["reviewing","monitoring","closed"].includes(b.status))return j({error:"invalid_status"},400);const t=now(),z=await env.DB.prepare("UPDATE risks SET reviewer=?,review_date=?,root_cause=?,contributing_factors=?,corrective_action=?,owner=?,due_date=?,outcome=?,residual_severity=?,follow_up_date=?,lessons_learned=?,status=?,updated_at=? WHERE id=?").bind(String(v.reviewer).trim(),v.reviewDate||null,String(v.rootCause).trim(),String(v.contributingFactors||""),String(v.correctiveAction).trim(),String(v.owner||""),v.dueDate||null,String(v.outcome||""),String(v.residualSeverity||""),v.followUpDate||null,String(v.lessonsLearned||""),b.status,t,x[1]).run();if(!z.meta.changes)return j({error:"not_found"},404);const row=await env.DB.prepare("SELECT * FROM risks WHERE id=?").bind(x[1]).first();return j({id:row.id,caseNo:caseNo(row),status:row.status})}
if(p==="/api/quality/list"&&m==="GET"){let {results}=await env.DB.prepare("SELECT * FROM quality_documents ORDER BY updated_at DESC").all();results=results.map(r=>({...r,docNo:r.doc_no,budgetYear:r.budget_year,monthName:r.month_name,formData:JSON.parse(r.form_data||"{}"),authorName:r.author_name,reviewerName:r.reviewer_name,reviewerNote:r.reviewer_note,reviewedAt:r.reviewed_at,signedBy:r.signed_by,signedAt:r.signed_at}));return j({items:results,documents:results})}
if(p==="/api/quality/create"&&m==="POST"){const b=await req.json(),typ=String(b.docType||"");if(!["monthly","rca","aar","profile"].includes(typ))return j({error:"invalid_type"},400);const by=Number(b.budgetYear||2569),title=String(b.title||"").trim();if(!title)return j({error:"title_required"},400);const n=await env.DB.prepare("SELECT COUNT(*) n FROM quality_documents WHERE doc_type=? AND budget_year=?").bind(typ,by).first(),prefix=typ==="monthly"?"REV":typ==="profile"?"RISK-PROFILE":typ.toUpperCase(),docNo=`${prefix}-${by}-${String(Number(n.n)+1).padStart(3,"0")}`,id=uid(),t=now(),st=String(b.status||"draft");await env.DB.prepare("INSERT INTO quality_documents(id,doc_type,doc_no,budget_year,month_name,title,form_data,status,author_name,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(id,typ,docNo,by,String(b.monthName||""),title,JSON.stringify(b.formData||{}),st,String(b.authorName||"นายมนูศักดิ์ อยู่บาง"),t,t).run();return j({id,docNo,status:st},201)}
x=p.match(/^\/api\/quality\/([^/]+)$/);if(x&&m==="PUT"){const b=await req.json(),cur=await env.DB.prepare("SELECT * FROM quality_documents WHERE id=?").bind(x[1]).first();if(!cur)return j({error:"not_found"},404);const allowed=new Set(["draft","sent_review","needs_edit","approved","ready_ha"]),st=allowed.has(String(b.status||""))?String(b.status):cur.status,t=now(),reviewed=["needs_edit","approved","ready_ha"].includes(st)?t:cur.reviewed_at,signed=["approved","ready_ha"].includes(st)?t:cur.signed_at,fd=b.formData??JSON.parse(cur.form_data||"{}");await env.DB.prepare("UPDATE quality_documents SET month_name=?,title=?,form_data=?,status=?,reviewer_name=?,reviewer_note=?,reviewed_at=?,signed_by=?,signed_at=?,updated_at=? WHERE id=?").bind(String(b.monthName??cur.month_name??""),String(b.title??cur.title??""),JSON.stringify(fd||{}),st,b.reviewerName??cur.reviewer_name,b.reviewerNote??cur.reviewer_note,reviewed,b.signedBy??cur.signed_by,signed,t,x[1]).run();return j({id:x[1],docNo:cur.doc_no,status:st,reviewerName:b.reviewerName??cur.reviewer_name,signedBy:b.signedBy??cur.signed_by,signedAt:signed})}
return env.ASSETS.fetch(req)}catch(e){return j({error:e.message},500)}}};